### ISSUE TITLE
Using double filters for both gatewayClass and ingressClass at the same time results in incorrect DNS

### ISSUE THREAD

**Issue by samip5** [k8s-gateway/k8s_gateway#48]
Hey @KuxaBeast!

I was testing this functionality after it getting merged, and noticed that if you have ingressClass and gatewayClass set, with two domains.

Querying for sub.domain.com results in the log of `sub.domain.com.domain.com` and as that doesn't exist NXDOMAIN.

**Comment by samip5** [comment]
The same happens with just a single filter. 🤔

**Comment by KuxaBeast** [comment]
I will look into it. I always only tried just one at a time, so this must have had slipped my fingers.

**Comment by samip5** [comment]
I think this only happens if you have HTTPRoute and Ingress for the same hostname.

So like both filters get the same hostname when this issue occurs.

**Comment by KuxaBeast** [comment]
@samip5 can you send me your config so I can reproduce your exact case?

**Comment by samip5** [comment]
The values used:

```
image:
      registry: ghcr.io
      repository: k8s-gateway/k8s_gateway
      tag: 1.0.3
      pullPolicy: IfNotPresent

    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN} ${SECRET_DOMAIN_LEGACY}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: "10.10.12.249"
      externalTrafficPolicy: Cluster
    watchedResources: ["Ingress", "HTTPRoute"]

    filters:
      ingressClasses: "internal"
      gatewayClasses: "internal"
```

This seemed to produce wierd AF results, but keep in mind Ingress and HTTPRoute are returning same hostnames, so that could be what's triggering it.
