### ISSUE TITLE
Request: Wildcard DNS support

### ISSUE THREAD

**Issue by hunbalazs** [k8s-gateway/k8s_gateway#57]
Currently hostnames are looked up with binary compare so a wildcard entry has no effect
(except if you look it up like this `nslookup *.example.com`, which is invalid)

**Comment by samip5** [comment]
Could you elaborate? Do you mean that if there's HTTPRoute or Ingress with a wildcard?

**Comment by hunbalazs** [comment]
Exactly.

For example one can create an ingress like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "*.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
```
In this case lookups for these domains should return the IP of the above ingress:
```
$ nslookup foo.bar.com -> IP of ingress-wildcard-host
$ nslookup anything.foo.com -> IP of ingress-wildcard-host
```
But sub-subdomains should not get resolved:
```
$ nslookup something.anything.foo.com -> NXDOMAIN
```

More info: https://en.wikipedia.org/wiki/Wildcard_DNS_record
